### ISSUE TITLE
Issue 1 user can search for stocks

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/Stock-watcher#1]
## 📐 Plan

Create a responsive home page containing a list that will hold a list of stocks, and a search bar to search for specific ticker symbols. 

## 🖼️ Wireframe
![Home Page - Empty List](https://user-images.githubusercontent.com/75342275/108892699-094d4c80-75c5-11eb-8945-216d3c2ddb25.png)

## ✅ Task List

- [x] Create html file and html skeleton
- [x] Create styles.css and main.js files
- [x] link files to html
- [x] import fonts
- [x] link to font awesome cdn
- [x] Add search bar to html - form that includes input and search icon
- [x] add styling to container class
- [x] create layout classes 
- [x] style search bar input
- [x] style search bar icon
- [x] add watchlist
- [x] style watchlist
- [x] Add media queries for responsiveness
- [x] Check html an find ways to better structure, if at all possible
- [x] check css and generalize reusable classes.
- [x] In main.js, query dom for search bar 
- [x] add event listener to home page and listen for input event
- [x] create a single function for sending requests to alphavantage.
- [x] create auto complete function and call request function with proper variables
- [x] test request function since this will probably be used often
- [x] add event listener to search icon and listen for 'submit' event
- [x] create function that sends and http request to alphavantage to. get daily stats
- [x] create request to get overview data from alphavantage
- [x] clean up code for sendRequestAlphaVantage function
- [x] create function for sending requests to yahoo finance
- [x] create request to get top stories from CNBC
- [x] create request to get individual stock news from CNBC
- [x] add event listener to window to get trending stories on load
- [x] parse responses from CNBC 
- [x] console log the returns to ensure data has been received 
- [x] Clean up and improve code 
- [x] test all other functionality
- [x] fix any errors or bugs
