### ISSUE TITLE
Issue 2 user can view stock data

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/Stock-watcher#2]
## 📐 Plan

Create a responsive page for viewing details on a single stock. This Page will Display Stock stats and latest new relative to the selected stock. Searching for a stock should switch views from home page to overview page. 

## 🖼️ Wireframe

![Individual Stock Page](https://user-images.githubusercontent.com/75342275/109050795-aa540a00-768e-11eb-8ad8-944fb065525b.png)

## ✅ Task List

- [x] Remove Alpha vantage API request due to request per minut limit
- [x] Consolidate code for single API use from CNBC
- [x] Take request response for trending news and append this data to the DOM
- [x] create dummy list element
- [x] style dummy list element
- [x] recreate dummy list element in displayTrending function  
- [x] Create div to store overview page info in html
- [x] create header for overview page in html
- [x] style overview header in css
- [x] create div to store stats
- [x] create mock-up stats in html 
- [x] create a table for stats
- [x] style stats section in css
- [x] Add functionality to inputSubmit function to load data in stats section 
- [x] create a second request to alpha vantage for daily stats data(create function variable, 
- [x] append price data to DOM
- [x] append date data to DOM
- [x] append open and close price to DOM
- [x] append daily high and low prices to DOM
- [x] Append ticker symbol to DOM.
- [x] append company name to DOm
- [x] append 52wk high and low prices to DOM
- [x] append yield and volume data to DOM
- [x] Create function to handle view swapping
- [x] Add ul to stock page to hold related news
- [x] on input, send request, and create news items from data
- [x] check code for errors
- [x] check for responsiveness
- [x] test functionality
- [x] remove any unnecessary code
- [x] Clean up code, make it more legible and efficient
