### ISSUE TITLE
issue 3 user can save stock to watchlist

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/Stock-watcher#3]
## 📐 Plan

User can press the plus icon to save the stock to their watchlist. Clicking on this stock directly from the home page will display the stocks overview data.  

## 🖼️ Wireframe

![Screen Shot 2021-02-25 at 4 38 08 PM](https://user-images.githubusercontent.com/75342275/109238161-e028e980-7787-11eb-8b3d-b5956a17e2dc.png)

## ✅ Task List

- [x]  Add event listener to plus icon
- [x] define function to handle data save
- [x] save necessary data to a new data model property
- [x] close overview page
- [x] create list item for stock
- [x] append stock to watchlist
- [x] create function to change color of price depending on Profit or loss
- [x] save data to local storage before unload event 
- [x] Set all irrelevant data to null
- [x] generate previous data on load event.
- [x] test functionality
- [x] fix all bugs and clean up code
- [x] check for responsiveness
