### ISSUE TITLE
issue 4 - user can click on watchlist item and quick open its stat page

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/Stock-watcher#4]
## 📐 Plan

User can quick link to a saved stocks stats page by clicking on a watchlist item. No need to search!

## 🖼️ Wireframe

![Screen Shot 2021-03-01 at 4 37 52 PM](https://user-images.githubusercontent.com/75342275/109578683-7ae93700-7aac-11eb-9f37-0e7177094125.png)

## ✅ Task List

- [x]  Add event listener to watchlist and listen for click event
- [x] Define a call back function that references a function named openWatchlistItem
- [x] send request to get watchlist data and news
- [x] call the loadStats function to create stats page for selected stock
- [x]  Ensure page switches corrrectly
- [x] hide plus icon at top of stats page. 
- [x] ensure app is mobile responsive
- [x] check for bugs
