### ISSUE TITLE
Issue 5 - user can delete stock from watchlist

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/Stock-watcher#5]
## 📐 Plan

User can click on pencil icon to display delete button. When a delete button is presses, the item will be removed from watchlist and data model. 

## 🖼️ Wireframe

![Screen Shot 2021-03-02 at 11 23 02 AM](https://user-images.githubusercontent.com/75342275/109703143-fcdb6d80-7b49-11eb-90e1-e4aea3efa9f9.png)

## ✅ Task List

- [x]  Add event listener to pencil icon
- [x] define function to handle displaying delete buttons
- [x] When clicked, change content of price column in watchlist items
- [x] on click remove list item from dom
- [x] loop through data model to delete item
- [x] ensure updated data model saves to local storage correctly. 
- [x] check for bugs and clean up code.
- [x] check for responsiveness
- [x] make any final adjustments.
